version: "3.9"
services:
  api:
    build: ./backend
    volumes: ["./backend:/app"]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on: [redis]
    ports: ["8000:8000"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  front:
    stdin_open: true
    tty: true
    image: node:20
    working_dir: /app
    volumes: ["./frontend/frontend:/app"]
    command: sh -c "npm install && npm run dev -- --host"
    ports: ["5173:5173"]
    depends_on: [api]